Arguments Provided for the Clinical Trials Meta Analysis Task Evaluator:
Task:         binary_outcomes
Output Path:  /scratch/yun.hy/llm-meta-analysis/evaluation/outputs/binary_outcomes/mistral7B_binary_outcomes_test_output_20240403-16:03:23.json
Metrics Path: /scratch/yun.hy/llm-meta-analysis/evaluation/metrics/binary_outcomes/

Traceback (most recent call last):
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 104, in __preprocess_binary_outcomes_results
    cleaned_yaml_string = clean_yaml_output(model_output)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/utils.py", line 153, in clean_yaml_output
    cleaned_output = "".join(cleaned_output)
                     ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, tuple found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 263, in <module>
    task_evaluator.run_evaluation()
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 219, in run_evaluation
    self.__preprocess_binary_outcomes_results()
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 108, in __preprocess_binary_outcomes_results
    print(f"Error parsing yaml string: {cleaned_yaml_string}")
                                        ^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'cleaned_yaml_string' where it is not associated with a value
Arguments Provided for the Clinical Trials Meta Analysis Task Evaluator:
Task:         continuous_outcomes
Output Path:  /scratch/yun.hy/llm-meta-analysis/evaluation/outputs/continuous_outcomes/mistral7B_continuous_outcomes_test_output_20240403-17:59:45.json
Metrics Path: /scratch/yun.hy/llm-meta-analysis/evaluation/metrics/continuous_outcomes

Traceback (most recent call last):
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 172, in __preprocess_continuous_outcomes_results
    cleaned_yaml_string = clean_yaml_output(model_output)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/utils.py", line 153, in clean_yaml_output
    cleaned_output = "".join(cleaned_output)
                     ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, tuple found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 263, in <module>
    task_evaluator.run_evaluation()
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 221, in run_evaluation
    self.__preprocess_continuous_outcomes_results()
  File "/scratch/yun.hy/llm-meta-analysis/evaluation/scripts/../evaluate_output.py", line 176, in __preprocess_continuous_outcomes_results
    print(f"Error parsing yaml string: {cleaned_yaml_string}")
                                        ^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'cleaned_yaml_string' where it is not associated with a value
